### PR TITLE
Inspect additional columns for non-integer values

### PR DESCRIPTION
**Pull request by warwickmm**
This modifies the `NonIntegerVotes` class to also inspect the `absentee`, `early_voting`, `election_day`, `mail`, and `provisional` columns for non-integer values.

### CODE REVIEW

**Comment by warwickmm** [comment]
I ran this test on the state repos and it found a few more non-integer values that will need to be addressed:

* Indiana
  ```
   ======================================================================
   FAIL: test_format (format_tests.test_format.FileFormatTests) [2018/20181106__in__general__precinct.csv]
   ----------------------------------------------------------------------
   Traceback (most recent call last):
     File "/home/ken/documents/code/openelections-format-tests/format_tests/test_format.py", line 54, in test_format
       self.assertTrue(passed, message)
   AssertionError: False is not true :

   2018/20181106__in__general__precinct.csv

   * There are 1 rows with votes that aren't integers:

           Headers: ['county', 'precinct', 'office', 'district', 'candidate', 'party', 'votes', 'absentee', 'election_day', 'provisional', 'early_voting']:
           Row 25334: ['Gibson', 'PAT2', 'Secretary of State', '', 'Cast Votes', '', '113', '', '77', '', '0.36']

   ======================================================================
   FAIL: test_format (format_tests.test_format.FileFormatTests) [2018/counties/20181106__in__general__gibson__precinct.csv]
   ----------------------------------------------------------------------
   Traceback (most recent call last):
     File "/home/ken/documents/code/openelections-format-tests/format_tests/test_format.py", line 54, in test_format
       self.assertTrue(passed, message)
   AssertionError: False is not true :

   2018/counties/20181106__in__general__gibson__precinct.csv

   * There are 1 rows with votes that aren't integers:

           Headers: ['county', 'precinct', 'office', 'district', 'candidate', 'party', 'early_voting', 'election_day', 'votes']:
           Row 623: ['Gibson', 'PAT2', 'Secretary of State', '', 'Cast Votes', '', '0.36', '77', '113']

   ======================================================================
   FAIL: test_format (format_tests.test_format.FileFormatTests) [2018/counties/20181106__in__general__jennings__precinct.csv]
   ----------------------------------------------------------------------
   Traceback (most recent call last):
     File "/home/ken/documents/code/openelections-format-tests/format_tests/test_format.py", line 54, in test_format
       self.assertTrue(passed, message)
   AssertionError: False is not true :

   2018/counties/20181106__in__general__jennings__precinct.csv

   * There are 1 rows with votes that aren't integers:

           Headers: ['precinct', 'office', 'district', 'candidate', 'party', 'votes', 'election_day', 'absentee', 'provisional']:
           Row 497: ['0009 GENEVA 3', 'State Representative', '67', 'CORDELLE FEUSTON', 'DEM', '69', '0.55', '14', '0']
  ```

* Texas
  ```
   ======================================================================
   FAIL: test_format (format_tests.test_format.FileFormatTests) [2018/counties/20180306__tx__primary__bosque__precinct.csv]
   ----------------------------------------------------------------------
   Traceback (most recent call last):
     File "/home/ken/documents/code/openelections-format-tests/format_tests/test_format.py", line 54, in test_format
       self.assertTrue(passed, message)
   AssertionError: False is not true :

   2018/counties/20180306__tx__primary__bosque__precinct.csv

   * There are 1 rows with votes that aren't integers:

           Headers: ['county', 'precinct', 'office', 'district', 'candidate', 'party', 'votes', 'early_voting', 'election_day']:
           Row 817: ['Bosque', 'Total', 'Governor', '', 'Under Votes', 'DEM', '15', '4', '10.1']

   ======================================================================
   FAIL: test_format (format_tests.test_format.FileFormatTests) [2014/counties/20141104__tx__general__chambers__precinct.csv]
   ----------------------------------------------------------------------
   Traceback (most recent call last):
     File "/home/ken/documents/code/openelections-format-tests/format_tests/test_format.py", line 54, in test_format
       self.assertTrue(passed, message)
   AssertionError: False is not true :

   2014/counties/20141104__tx__general__chambers__precinct.csv

   * There are 2 rows with votes that aren't integers:

           Headers: ['county', 'precinct', 'office', 'district', 'candidate', 'party', 'absentee', 'early_voting', 'election_day', 'votes']:
           Row 205: ['Chambers', '8- COVE', 'U.S. House', '36', 'Brian Babin', 'REP', '1.092', '28', '503', '561']
           Row 211: ['Chambers', 'Total', 'U.S. House', '36', 'Brian Babin', 'REP', '5841.092', '198', '3611', '3123']

   ======================================================================
   FAIL: test_format (format_tests.test_format.FileFormatTests) [2016/counties/20161108__tx__general__wilson__precinct.csv]
   ----------------------------------------------------------------------
   Traceback (most recent call last):
     File "/home/ken/documents/code/openelections-format-tests/format_tests/test_format.py", line 54, in test_format
       self.assertTrue(passed, message)
   AssertionError: False is not true :

   2016/counties/20161108__tx__general__wilson__precinct.csv

   * There are 1 rows with votes that aren't integers:

           Headers: ['county', 'precinct', 'office', 'district', 'candidate', 'party', 'early_voting', 'election_day', 'provisional', 'absentee', 'votes']:
           Row 103: ['Wilson', 'Total', 'President', '', 'Donald Trump', 'REP', '6457', '6994', '7', '532.08', '13998']
  ```

**Comment by warwickmm** [comment]
@dwillis, let me know if you have any questions or concerns about this.

**Comment by dwillis** [comment]
@warwickmm no questions or concerns - this is much-needed.

**Comment by warwickmm** [comment]
Thanks @dwillis.  I'm going to go ahead and merge this.  I have some additional changes in the queue.

**Pull request merged**
